name: "PHP Static Analyze"

on:
  push:
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

jobs:
  php-cs-fixer:
    name: "PHPStan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Setup PHP"
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
      - name: "Install Automatic Composer Prefetcher"
        run: composer global require --no-progress --no-scripts --no-plugins narrowspark/automatic-composer-prefetcher:dev-master

      - name: "analyze php code"
        run: |
          echo ::group::Composer install
          composer update --no-progress --no-suggest --no-interaction --ansi
          echo ::endgroup::

          composer phpstan
